### ISSUE TITLE
Generation Error on Mac

### ISSUE THREAD

**Issue by jllamas** [encharm/Font-Awesome-SVG-PNG#10]
I'm getting an error when I run the script. I do have rsvg-convert installed

$ which rsvg-convert
/usr/local/bin/rsvg-convert

$ rsvg-convert -v
rsvg-convert version 2.36.3

$  node font-awesome-svg-png --color white --sizes 128,256
Downloading latest icons.yml ...
Downloading latest fontawesome-webfont.svg ...
Generating icon glass
Generating icon music
Generating icon search
Generating icon envelope-o
Generating icon heart
Generating icon star
Generating icon star-o
Generating icon user
Generating icon film
Generating icon th-large
Generating icon th
Generating icon th-list
Generating icon check
Generating icon times
Generating icon search-plus
Generating icon search-minus
Generating icon power-off
Generating icon signal
Generating icon cog
Generating icon trash-o
Generating icon home
Generating icon file-o
Generating icon clock-o
Generating icon road
Generating icon download
Generating icon arrow-circle-o-down
Generating icon arrow-circle-o-up
Generating icon inbox
Generating icon play-circle-o
Generating icon repeat
Generating icon refresh
Generating icon list-alt
Generating icon lock
Generating icon flag
Generating icon headphones
Generating icon volume-off
Generating icon volume-down
Generating icon volume-up
Generating icon qrcode
Generating icon barcode
Generating icon tag
Generating icon tags
Generating icon book
Generating icon bookmark
Generating icon print
Generating icon camera
Generating icon font
Generating icon bold
Generating icon italic
Generating icon text-height
Generating icon text-width
Generating icon align-left

child_process.js:935
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
    at errnoException (child_process.js:988:11)
    at ChildProcess.spawn (child_process.js:935:11)
    at exports.spawn (child_process.js:723:9)
    at /Users/jllamas/Desktop/Projects/Exoplanet Archive/node_modules/font-awesome-svg-png/font-awesome-svg-png.js:124:25
    at iterate (/Users/jllamas/Desktop/Projects/Exoplanet Archive/node_modules/font-awesome-svg-png/node_modules/async/lib/async.js:134:13)
    at ChildProcess.<anonymous> (/Users/jllamas/Desktop/Projects/Exoplanet Archive/node_modules/font-awesome-svg-png/node_modules/async/lib/async.js:145:25)
    at ChildProcess.g (events.js:180:16)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)

**Comment by Rush** [comment]
It is possible now with `--no-png`.
