### ISSUE TITLE
svgs are variable size for me

### ISSUE THREAD

**Issue by yanfali** [encharm/Font-Awesome-SVG-PNG#17]
I feel like I'm missing something in my environment. When I run svg-png from npm (v1.1.1) my svgs are not the uniform 2048x2048 exports  you have in the repo in black.

Here's my environment:

OSX 10.9.4
brew 0.9.5
librsvg: stable 2.36.3 (bottled)

The issue I have is the SVGs I'm generating appear to be variable size and have a huge amount of white space around them. I'm trying to use them with grunt-webfont to spin a custom font set. The documentation doesn't seem to list any switches for setting the max dimensions of the svgs or controlling their white space.

I noticed when I downloaded from the repo, your black icon set has uniform 2048x2048 icons with minimal white space. Can you please let me know how I can repeat your results? Is it because I'm using brew and not mac ports?

Thanks

**Comment by Rush** [comment]
Can you try now?

**Comment by yanfali** [comment]
I'll try and give a shot tomorrow. Thanks for working on this.
