### ISSUE TITLE
Attribute main in bower

### ISSUE THREAD

**Issue by brunowego** [encharm/Font-Awesome-SVG-PNG#24]
The main attribute is wrong, need set path to files.

```js
"main": "Font-Awesome-SVG-PNG.js",
```

#23

**Comment by synapticism** [comment]
The `bower.json` file should validate just fine but the package needs a version bump. See #23 again.

**Comment by brunowego** [comment]
If you work with [wiredep](https://github.com/stephenplusplus/grunt-wiredep) package will add automatically the files. Wiredep uses main attribute to include files.

**Comment by synapticism** [comment]
This is `main` right now:

```
"main": "Font-Awesome-SVG-PNG.js",
```

What's wrong here, the path? Capitalization? Something else?

**Comment by brunowego** [comment]
Thanks @synapticism, not is wrong. I use [grunt-webfont](https://github.com/sapegin/grunt-webfont) to generate fonts with SVG files.
