### ISSUE TITLE
add gh-pages branch to work with d3moji

### ISSUE THREAD

**Issue by timelyportfolio** [encharm/Font-Awesome-SVG-PNG#31]
Thanks so much for sharing this fine work.  I have used the `svg` in multiple projects.  I thought it would be nice to also make these available in `d3moji` (see https://github.com/mathisonian/d3moji/issues/2).  Would you consider adding a gh-pages branch with all the `svg` so that we can use them?    If not, I can easily fork and do the same on my end, but I wanted to make sure you got all the credit.  Thanks for considering.

If some additional information might be helfpul, see this [line](https://github.com/mathisonian/d3moji/blob/master/d3moji.js#L31) from `d3moji` to see how it accesses the `svg` from the twitter emoji cdn.

**Comment by Rush** [comment]
Hi, thanks for the kind words. Yes I would definitely apply such a pull request with all the proper credits going your way for th ework. I am not too familiar with `d3moji` so if you require anything from me you would have to simplify it. :)

**Comment by timelyportfolio** [comment]
Would it be possible for you to create an empty `gh-pages` branch (see this [article](https://help.github.com/articles/creating-project-pages-manually/)) so I can submit a pull on that branch?  I envision the pull to simply be a copy of the black svg directory as a start.

Thanks again.

**Comment by Rush** [comment]
@timelyportfolio Done. https://github.com/encharm/Font-Awesome-SVG-PNG/tree/gh-pages

**Comment by timelyportfolio** [comment]
Thanks for this.  I'll see if I can help incorporate in `d3moji`.
