### ISSUE TITLE
version 4.4 ?

### ISSUE THREAD

**Issue by jm4r7in** [encharm/Font-Awesome-SVG-PNG#35]
:+1:

**Comment by derwaldgeist** [comment]
:+1:
Yes, there are very interesting new icons inside. Would love to see an update of the SVG versions.

**Comment by GladLock** [comment]
Yeah, would it be possible for somebody to update the black and white icons with the updated set?

**Comment by VinSpee** [comment]
I would love to see this as well

**Comment by huphtur** [comment]
For those that can't wait, you can use the [IconMoon App](https://icomoon.io/app/) to convert and download Font Awesome icons (including 4.4) to SVG, PNG, etc.

**Comment by FelisPhasma** [comment]
Thakns @huphtur, that's really helpful!

**Comment by osricmacon** [comment]
You can just download font awesome complete zip in node_module > font-awesome and it will work for 4.4 as well. I tried and it works

**Comment by derwaldgeist** [comment]
4.5 is out now, so we may close this in favor of #43... :-)
