### ISSUE TITLE
Use custom Hex colors?

### ISSUE THREAD

**Issue by funkenstrahlen** [encharm/Font-Awesome-SVG-PNG#38]
Is there any way I can use a custom hex color instead of the predefined javascript color set?

**Comment by funkenstrahlen** [comment]
Managed to solve it myself. Just had to put the color as Hex:

`font-awesome-svg-png --color "#0370E9" --svg --no-png --dest blue`

**Comment by rinogo** [comment]
This should be in `README.md`.

**Comment by tobiasmuehl** [comment]
Note the required double quotes, hash sign and uppercase letters

**Comment by Rush** [comment]
Could you send a PR with a Readme improvement? Thanks
