### ISSUE TITLE
Version 4.5

### ISSUE THREAD

**Issue by derwaldgeist** [encharm/Font-Awesome-SVG-PNG#43]
It's out now, and I would like to use the new icons.

**Comment by calvinjuarez** [comment]
Mine is not as robust a system, but it's based on the 4.5.0 release: https://github.com/calvinjuarez/SVG-Awesome

**Comment by jpdevries** [comment]
+1

**Comment by Rush** [comment]
Just merged #44

**Comment by derwaldgeist** [comment]
Thanks!
