### ISSUE TITLE
1.1.5 has no bower release

### ISSUE THREAD

**Issue by Ortintzki** [encharm/Font-Awesome-SVG-PNG#47]
Currently when I try to install the icons using `bower install font-awesome-svg-png` the only versions that are available are 1.1.2 and 1.1.0.    This means that several icons that were added in 1.1.5 (for instance, the tv icon) are not available when doing a bower install.  Could a release that includes these new icons be distributed?

**Comment by Ortintzki** [comment]
I think with all the icon updates this could be released as 1.2.0; I was confused by the version mismatching on npm and bower.  npm has a version tagged 1.1.5 while bower has 1.1.2.

**Comment by Rush** [comment]
@synapticism Any thoughts?

**Comment by synapticism** [comment]
@Rush Bower works from the git tag so you need to create a tag or release for the repo. Bump the release version to 1.1.5 and Bower should pick it up: 
https://github.com/encharm/Font-Awesome-SVG-PNG/releases

**Comment by Rush** [comment]
@synapticism thanks, done.

**Comment by vcmJonasTarnowetzki** [comment]
@Rush @synapticism Thanks for the quick work, I really appreciate it.

**Comment by Ortintzki** [comment]
Thank you for dealing with this so quickly.
