### ISSUE TITLE
google-plus.svg has parts cropped out

### ISSUE THREAD

**Issue by tikitariki** [encharm/Font-Awesome-SVG-PNG#48]
The `google-plus.svg` logo, both white and black, have parts of the logo cropped out.

https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/google-plus.svg
https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/white/svg/google-plus.svg

**Comment by wenom64** [comment]
If someone need a quick fix, set viewBox of this icon to "0 -200 1792 2312"

**Comment by Rush** [comment]
Fixed.
