### ISSUE TITLE
Include a version of the SVG files with fill set to currentColor

### ISSUE THREAD

**Issue by christianmagill** [encharm/Font-Awesome-SVG-PNG#51]
It would be great if you could include in the repo a version of the SVG files with fill set to currentColor.

I'd love to just be able to add this via bower and immediately get to work using the files.

**Comment by Ciantic** [comment]
Why? The black icons seems to not have a fill set, this means you can colorize them with CSS just using `fill: #ff0;`

**Comment by Rush** [comment]
@christianmagill npm package now includes all black and white icons. I hear bower is deprecated.
