### ISSUE TITLE
motorcycle png is cropped

### ISSUE THREAD

**Issue by codazoda** [encharm/Font-Awesome-SVG-PNG#53]
The motorcycle character, in png version, is cropped at the right and left side.

**Comment by watert** [comment]
lots of icons are cropped, like wifi icon, seems viewBox value of `0 0 1792 1792` if not enough for some icons, but change to `-200 -200 2200 2200`will do the trick, hope will be a better solution

**Comment by Rush** [comment]
@watert unfortunately I don't have time to investigate at this moment but I'd accept a PR that fixes it in some proper way.

**Comment by Rush** [comment]
Fixed, see https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/32/motorcycle.png

The newest version also adjusts properly for pixel grid.
