### ISSUE TITLE
Issue with Font Awesome 4.7.0

### ISSUE THREAD

**Issue by steenbag** [encharm/Font-Awesome-SVG-PNG#61]
Hello, I've recently installed the package on a new system, and as a result installed fresh dependencies. It looks as though Font Awesome have tweaked the structure of fontawesome-webfont.svg, so the getFontData parsing no longer works as expected.

From a cursory inspection, it looks like there are a few glyph tags without unicode attributes (e.g. glyph-name=".notdef",  glyph-name=".null").

On my local system I have Font Awesome 4.6.3, which still works correctly.

**Comment by Rush** [comment]
Please see latest changes. I apologize for not attending to this repo. Hopefully this latest update amends my absence.
