### ISSUE TITLE
Bower deprecation; adding complete package to npm?

### ISSUE THREAD

**Issue by synapticism** [encharm/Font-Awesome-SVG-PNG#67]
[Bower is effectively deprecated](https://github.com/bower/bower/issues/2298), would it be possible to expand what's offered through npm to include source files for those of us who roll out own SVG sprite sheets? The issue is the presence of `black` and `white` in `.npmignore`; without this, all files will be available, and it'll skip a compilation step for those of us rolling our own SVG sprite sheets.

**Comment by Rush** [comment]
I will publish new version this week. I'd like to fix some pixel perfection problems for some of the generated sizes.

**Comment by Rush** [comment]
Fixes, use version 1.2.0

**Comment by synapticism** [comment]
Thanks, I can confirm it works as expected 👍
