### ISSUE TITLE
Nice job! See my repo `local-icons` in order to use these icons in a very easy way.

### ISSUE THREAD

**Issue by Dellos7** [encharm/Font-Awesome-SVG-PNG#73]
Hello!

Thanks for all the amazing job. I have created a repo - https://github.com/Dellos7/local-icons - so people can use these kind of icons in a very easy way - only copy/paste and avoid to include external CSS stylesheets.

May you add it to the readme? Thanks!

**Comment by Rush** [comment]
Nice job but how is your work related to Font-Awesome-SVG-PNG?

**Comment by Dellos7** [comment]
I'm using your icons in order to make available the CSS classes and referenced your repo in the README so people can check out from where I've taken the icons and check out also your work.

**Comment by Rush** [comment]
@Dellos7 please send a PR with the README change proposal

**Comment by Dellos7** [comment]
Hello @Rush,

I have created the PR #74 with the README change proposal.

Thanks!
